on:
  schedule:
    # At every 120th minute.
    - cron: '*/120 * * * *'
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navi-language/setup-navi@v1
        with:
          navi-version: v0.9.1-nightly-20240107
      - name: Perform
        env:
          CI: 1
          FEISHU_WEBHOOK_KEY: ${{ secrets.FEISHU_WEBHOOK_KEY }}
        run: |
          navi run
          git config --global user.name "RSS Bot"
          git config --global user.email "rss-bot@longbridge-inc.com"
          timestamp=$(date -u)
          git add -A && git commit -m "Update check state ${timestamp}." || exit 0
          git push
