name: Run
on:
  schedule:
    # At every 120th minute.
    - cron: "*/120 * * * *"
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navi-language/setup-navi@v1
        with:
          navi-version: v0.16.0
      - name: Perform
        env:
          CI: 1
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          navi run
          git config --global user.name "RSS Bot"
          git config --global user.email "rss-bot@longbridge-inc.com"
          timestamp=$(date -u)
          git add -A && git commit -m "Update check state ${timestamp}." || exit 0
          git push
